version: '3'
services:
  my-mongo-service:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example      
  my-server-api-service:
    container_name: server
    build: 
      dockerfile : Dockerfile.dev
      context: ./server
    ports:
      - "30001:30001"
    environment:
      - SERVER_API_PORT=30001
      - MONGODB_URI=mongodb://my-mongo-service:27017
    restart: always  
    depends_on:
      - my-mongo-service
  client-service:
    container_name: client
    build: 
      dockerfile : Dockerfile.dev
      context: ./public
    ports:
      - "4200:4200"
    restart: always
    depends_on:
      - my-server-api-service
      