apiVersion: v1
kind: Service
metadata:
  name: client-web-service
  namespace: weatherapp
spec:
  selector:
    component: client-web
  ports:
  - port: 4200
    targetPort: 4200
    nodePort: 31515
  type: NodePort

