apiVersion: v1
kind: Service
metadata:
  name: server-api-service
  namespace: weatherapp
spec:
  selector:
    component: server-api
  ports:
  - port: 30001
    targetPort: 30001
    # nodePort: 31516
  # type: NodePort
